= Head-First Reactive Workshop
Stephane Maldini, Ben Hale, Madhura Bhave - Pivotal
:sectanchors: true
:source-highlighter: prettify
:icons: font
:toc:
:spring-boot-version: 2.1.7.RELEASE
:spring-framework-version: 5.1.9.RELEASE
:reactor-version: CALIFORNIUM-SR10
:spring-framework-doc-base: https://docs.spring.io/spring-framework/docs/{spring-framework-version}
:java-version: JDK 11

This repository hosts a complete workshop on Spring + Reactor.
Just follow this Guide and create your first reactive Spring application!
Each step of this workshop has its companion commit in the git history with a detailed commit message.

At the end of the workshop, we will have created three applications:

* `stock-quotes` is a functional WebFlux app which streams stock quotes
* `stock-details` is an annotation-based WebFlux app using a reactive datastore
* `trading-service` is an annotation-based WebFlux app that consumes data from `stock-quotes` and `stock-details`

Reference documentations can be useful while working on those apps:

* https://projectreactor.io/docs[Reactor Core documentation]
* https://projectreactor.io/docs/core/release/api/reactor/core/publisher/Flux.html[API documentation for Flux]
* https://projectreactor.io/docs/core/release/api/reactor/core/publisher/Mono.html[API documentation for Mono]
* Spring WebFlux
{spring-framework-doc-base}/spring-framework-reference/web.html#web-reactive[reference documentation]
and {spring-framework-doc-base}/javadoc-api/[javadoc]

Clone the repository:

git clone https://github.com/reactor/head-first-reactive-with-spring-and-reactor.git

We will start off by creating the Trading Service application which gets data from the Stock Quotes application.

== Stock Quotes application

=== Create this application

Go to `https://start.spring.io` and create a Maven project with Spring Boot {spring-boot-version},
with groupId `io.spring.workshop` and artifactId `stock-quotes`. Select the `Spring Reactive Web` and `Spring Boot Devtools` and `Lombok` dependencies.
Unzip the given file into a directory and import that application into your IDE.

If generated right, you should have a main `StockQuotesApplication` class that looks like this:

[source,java]
.stock-quotes/src/main/java/io/spring/workshop/stockquotes/StockQuotesApplication.java
----
include::../app-code/back-end/microservices/stock-quotes/src/main/java/io/spring/workshop/stockquotes/StockQuotesApplication.java[]
----

Edit your `application.properties` file to start the server on port 8081.

[source,properties]
.stock-quotes/src/main/resources/application.properties
----
include::../app-code/back-end/microservices/stock-quotes/src/main/resources/application.properties[]
----

Launching it from your IDE or with `mvn spring-boot:run` should start a Netty server on port 8081.
You should see in the logs something like:

[source,bash]
----
INFO 2208 --- [  restartedMain] o.s.b.web.embedded.netty.NettyWebServer  : Netty started on port(s): 8081
INFO 2208 --- [  restartedMain] i.s.w.s.StockQuotesApplication           : Started StockQuotesApplication in 1.905 seconds (JVM running for 3.075)
----

=== Create a Quote Generator

To simulate real stock values, we'll create a generator that emits such values at a specific interval.
Copy the following classes to your project.

[source,java]
.stock-quotes/src/main/java/io/spring/workshop/stockquotes/domain/Quote.java
----
include::../app-code/back-end/microservices/stock-quotes/src/main/java/io/spring/workshop/stockquotes/domain/Quote.java[]
----

[source,java]
.stock-quotes/src/main/java/io/spring/workshop/stockquotes/component/QuoteGenerator.java
----
include::../app-code/back-end/microservices/stock-quotes/src/main/java/io/spring/workshop/stockquotes/component/QuoteGenerator.java[]
----

Because we're working with `java.time.Instant` and Jackson, we should import the dedicated module in our app.

NOTE: The `QuoteGenerator` instantiates a `Flux<Quote>` that emits a `Quote` every 200 msec and can be **shared** between
multiple subscribers (look at the `Flux` operators for that). This instance is kept as an attribute for reusability.

[source,xml]
.stock-quotes/pom.xml
----
include::../app-code/back-end/microservices/stock-quotes/pom.xml[tags=jacksonJSR310]
----

=== Functional web applications with "WebFlux.fn"

Spring WebFlux comes in two flavors of web applications: annotation based and functional.
For this first application, we'll use the functional variant.

Incoming HTTP requests are handled by a `HandlerFunction`, which is essentially a function
that takes a ServerRequest and returns a `Mono<ServerResponse>`. The annotation counterpart
to a handler function would be a Controller method.

But how those incoming requests are routed to the right handler?

We're using a `RouterFunction`, which is a function that takes a `ServerRequest`, and returns
a `Mono<HandlerFunction>`. If a request matches a particular route, a handler function is returned;
otherwise it returns an empty `Mono`. The `RouterFunction` has a similar purpose as the `@RequestMapping`
annotation in `@Controller` classes.

Take a look at the code samples in
{spring-framework-doc-base}/spring-framework-reference/web.html#web-reactive-server-functional[the Spring WebFlux.fn reference documentation]

=== Create your first HandlerFunction + RouterFunction

First, create a `QuoteHandler` class and mark is as a `@Component`; this class will have all our handler functions as methods.
Let's inject our `QuoteGenerator` instance in our `QuoteHandler`.

Now create a `streamQuotes` handler that streams the generated quotes with the `"application/stream+json"` content type.

[source,java]
.stock-quotes/src/main/java/io/spring/workshop/stockquotes/component/QuoteHandler.java
----
include::../app-code/back-end/microservices/stock-quotes/src/main/java/io/spring/workshop/stockquotes/component/QuoteHandler.java[]
----

To route requests to that handler, you need to expose a `RouterFunction` to Spring Boot.
Create a `QuoteRouter` configuration class (i.e. annotated with `@Configuration`)
that creates a bean of type `RouterFunction<ServerResponse>`.

Modify that class so that GET requests to `"/quotes"` are routed to the handler you just implemented.

[source,java]
.stock-quotes/src/main/java/io/spring/workshop/stockquotes/component/QuoteRouter.java
----
include::../app-code/back-end/microservices/stock-quotes/src/main/java/io/spring/workshop/stockquotes/component/QuoteRouter.java[]
----

TIP: Since `QuoteHandler` is a component, you can inject it in `@Bean` methods as a method parameter.

Your application should now behave like this:

[source,bash]
----
$ curl http://localhost:8081/quotes -i -H "Accept: application/stream+json"
HTTP/1.1 200 OK
transfer-encoding: chunked
Content-Type: application/stream+json

{"ticker":"CTXS","price":84.0,"instant":1494841666.633000000}
{"ticker":"DELL","price":67.1,"instant":1494841666.834000000}
{"ticker":"GOOG","price":869,"instant":1494841667.034000000}
{"ticker":"MSFT","price":66.5,"instant":1494841667.231000000}
{"ticker":"ORCL","price":46.13,"instant":1494841667.433000000}
{"ticker":"RHT","price":86.9,"instant":1494841667.634000000}
{"ticker":"VMW","price":93.7,"instant":1494841667.833000000}
...
----

=== Integration tests with WebTestClient

Spring WebFlux (actually the `spring-test` module) includes a `WebTestClient`
that can be used to test WebFlux server endpoints with or without a running server.
Tests without a running server are comparable to MockMvc from Spring MVC where mock request
and response are used instead of connecting over the network using a socket.
The WebTestClient however can also perform tests against a running server.

You can check that your last endpoint is working properly with the following
integration test:

[source,java]
.stock-quotes/src/test/java/io/spring/workshop/stockquotes/component/integration/QuoteGeneratorTest.java
----
include::../app-code/back-end/microservices/stock-quotes/src/test/java/io/spring/workshop/stockquotes/component/integration/QuoteGeneratorTest.java[]
----

== Trading Service application

=== Create this application

Go to `https://start.spring.io` and create a Maven project with Spring Boot {spring-boot-version},
with groupId `io.spring.workshop` and artifactId `trading-service`. Select the `Spring Reactive Web` and `Spring Boot Devtools` and `Lombok` dependencies.
Unzip the given file into a directory and import that application into your IDE.

If generated right, you should have a main `TradingServiceApplication` class that looks like this:

[source,java]
.trading-service/src/main/java/io/spring/workshop/tradingservice/TradingServiceApplication.java
----
include::../app-code/back-end/microservices/trading-service/src/main/java/io/spring/workshop/tradingservice/TradingServiceApplication.java[]
----

Note that, by default, `spring-boot-starter-webflux` transitively brings `spring-boot-starter-reactor-netty`
and Spring Boot auto-configures Reactor Netty as a web server.

Spring Boot supports Tomcat, Undertow and Jetty as well.

=== Use the WebClient to stream JSON to the browser

In this section, we'll call our remote `stock-quotes` service to get Quotes from it, so we first need to:

* Copy over the `Quote` class to this application
* Add the Jackson JSR310 module dependency

[TIP]
====
Refer to the section `Stock Quotes application`.
====

Create a `QuotesClient` annotated with `@Component` and inject a `WebClient.Builder`. Now, create a method in the `QuotesClient` called
`quotesFeed` which will use the `webClient` to consume the stream of quotes via Server Sent Events (SSE).

NOTE: There are two ways to use a `WebClient`, directly via the static factory or by injecting the `WebClient.Builder`.
The latter is used by libraries such as Spring Cloud Sleuth that enrich `WebClient` with extra features.

[source,java]
.trading-service/src/main/java/io/spring/workshop/tradingservice/component/QuotesClient.java
----
include::../app-code/back-end/microservices/trading-service/src/main/java/io/spring/workshop/tradingservice/component/QuotesClient.java[]
----

Now create a `QuotesController` annotated with `@Controller` and inject it with the `QuotesClient`.
Add a method that responds to `"GET /quotes/feed"` requests with the `"text/event-stream"` content-type,
with a `Flux<Quote>` as the response body. The data can be retrieved from the `quotesFeed` method on `QuotesClient`.

[source,java]
.trading-service/src/main/java/io/spring/workshop/tradingservice/controller/QuotesController.java
----
include::../app-code/back-end/microservices/trading-service/src/main/java/io/spring/workshop/tradingservice/controller/QuotesController.java[]
----


You can test it by starting both applications. First, start the Stock Quotes application.
It can be started from your IDE or with `mvn spring-boot:run` and it should run a Netty server on port 8081.
You should see in the logs something like:

[source,bash]
----
INFO 2208 --- [  restartedMain] o.s.b.web.embedded.netty.NettyWebServer  : Netty started on port(s): 8081
INFO 2208 --- [  restartedMain] i.s.w.s.StockQuotesApplication           : Started StockQuotesApplication in 1.905 seconds (JVM running for 3.075)
----

Start the Trading Service application from your IDE or with `mvn spring-boot:run`. This should run a Netty server on port 8080.

[source,bash]
----
INFO 2208 --- [  restartedMain] o.s.b.web.embedded.netty.NettyWebServer  : Netty started on port(s): 8080
INFO 2208 --- [  restartedMain] i.s.w.t.TradingServiceApplication           : Started TradingServiceApplication in 1.905 seconds (JVM running for 3.075)
----

You can hit http://localhost:8080/quotes/feed to consume the stream of quotes.

Now, let's create another application that can provide the details for a trading company.

